# Generated by Django 3.2.1 on 2022-02-11 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0007_consumidor_processador_produtor_transportador'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateField(auto_now=True)),
                ('tipo', models.CharField(max_length=30)),
                ('quantidade', models.IntegerField(default=0)),
                ('Processador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.processador')),
                ('Produtor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.produtor')),
                ('Transportador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.transportador')),
            ],
        ),
    ]
