# Generated by Django 3.2.1 on 2022-02-14 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='DataFabricacao',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='product',
            name='TempoValidade',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='descricao',
            field=models.TextField(blank=True),
        ),
    ]
