# Generated by Django 3.2.1 on 2022-02-14 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20220211_1653'),
        ('product', '0003_auto_20220214_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='processador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.processador'),
        ),
        migrations.AlterField(
            model_name='product',
            name='transportador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.transportador'),
        ),
    ]
