# Generated by Django 3.2.1 on 2022-02-14 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20220211_1653'),
        ('product', '0004_auto_20220214_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='produtor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.produtor'),
        ),
    ]
