# Generated by Django 3.2.1 on 2022-02-14 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_product_produtor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='datafabricacao',
            field=models.DateField(blank=True, null=True),
        ),
    ]
