# Generated by Django 3.2.1 on 2022-02-16 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consumidor',
            old_name='userProdutor',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='processador',
            old_name='userProdutor',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='produtor',
            old_name='userProdutor',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='transportador',
            old_name='userProdutor',
            new_name='user',
        ),
    ]
