# Generated by Django 3.2.1 on 2022-02-09 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20220128_0006'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='CNPJ_company',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='cargo',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='birthday',
            field=models.DateField(blank=True),
        ),
    ]
