# Generated by Django 3.2.1 on 2022-02-10 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20220209_2236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='CNPJ_company',
        ),
        migrations.AddField(
            model_name='user',
            name='is_organic',
            field=models.BooleanField(default=False),
        ),
    ]
