# Generated by Django 3.2.1 on 2022-02-16 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateField(auto_now=True)),
                ('tipo', models.CharField(max_length=30)),
                ('quantidade', models.CharField(default='0', max_length=30)),
                ('descricao', models.TextField(blank=True)),
                ('datafabricacao', models.DateField(auto_now=True, null=True)),
                ('tempovalidade', models.CharField(default='0', max_length=30)),
                ('preço', models.IntegerField(default=0)),
                ('status', models.CharField(default='Anunciado', max_length=30)),
            ],
        ),
    ]
