# Generated by Django 3.2.1 on 2022-02-16 02:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='produtor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.produtor'),
        ),
    ]
