# Generated by Django 3.2.1 on 2022-02-14 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20220214_1232'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='DataFabricacao',
            new_name='datafabricacao',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Processador',
            new_name='processador',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Produtor',
            new_name='produtor',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='TempoValidade',
            new_name='tempovalidade',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Transportador',
            new_name='transportador',
        ),
    ]
