# Generated by Django 3.2.1 on 2022-02-16 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('product', '0002_product_produtor'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='categoria',
            field=models.IntegerField(choices=[(1, 'Primário'), (2, 'Secundário')], default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='subprodutos',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.product'),
        ),
        migrations.CreateModel(
            name='TransporteProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateTimeField(null=True)),
                ('data_fim', models.DateTimeField(null=True)),
                ('produto', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.product')),
                ('transportador', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.transportador')),
            ],
        ),
    ]
