# Generated by Django 3.2.1 on 2022-02-16 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20220216_1229'),
        ('product', '0003_auto_20220216_1202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transporteproduto',
            name='produto',
        ),
        migrations.AddField(
            model_name='transporteproduto',
            name='produto',
            field=models.ManyToManyField(null=True, to='product.Product'),
        ),
        migrations.RemoveField(
            model_name='transporteproduto',
            name='transportador',
        ),
        migrations.AddField(
            model_name='transporteproduto',
            name='transportador',
            field=models.ManyToManyField(null=True, to='users.Transportador'),
        ),
    ]
