# Generated by Django 3.2.1 on 2022-02-16 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20220216_1229'),
        ('product', '0004_auto_20220216_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transporteproduto',
            name='produto',
            field=models.ManyToManyField(to='product.Product'),
        ),
        migrations.AlterField(
            model_name='transporteproduto',
            name='transportador',
            field=models.ManyToManyField(to='users.Transportador'),
        ),
    ]
