# Generated by Django 3.2.1 on 2022-02-15 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_product_datafabricacao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='processador',
        ),
        migrations.RemoveField(
            model_name='product',
            name='transportador',
        ),
        migrations.AlterField(
            model_name='product',
            name='datafabricacao',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
