# Generated by Django 3.2.1 on 2022-01-27 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_set',
            field=models.BooleanField(default=False),
        ),
    ]
