# Generated by Django 3.2.1 on 2022-02-11 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_rename_user_produtor_userprodutor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consumidor',
            old_name='user',
            new_name='userProdutor',
        ),
        migrations.RenameField(
            model_name='processador',
            old_name='user',
            new_name='userProdutor',
        ),
        migrations.RenameField(
            model_name='transportador',
            old_name='user',
            new_name='userProdutor',
        ),
    ]
